### ISSUE TITLE
Stats gives a 404

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/road-completion#205] opened 2021-08-25 11:58 UTC
https://osmbe.github.io/road-completion/

**Comment by jbelien** [comment] 2021-08-25 12:43
Duplicate of #177

I don't exactly know why sometimes the report page is not built correctly...
I'll migrate to something else than Sapper to build the report page since it's a pretty simple page (when I have a bit of time).

**Closed as completed by jbelien** 2021-08-25 12:43 UTC
Labels: duplicate
